Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'rakelib/db/seeds.rake'
    - 'app/routes/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - 'rakelib/db/seeds.rake'

Style/BlockDelimiters:
  Exclude:
    - 'rakelib/**/*'
